image: node:latest

include:
  - project: 'devops/gitlab-ci-templates'
    file: '/.create_version_tag.yml'
  - project: 'devops/gitlab-ci-templates'
    file: '/.get_build_version.yml'

stages:
  - create_version_tag
  - get_build_version
  - deploy

deploy:
  stage: deploy
  except:
    - tags
    - schedules
    - triggers
  only:
    - master
    - /^rel_.*$/
  script:
    - export VERSION=$(cat current_version)
    - npm version "${VERSION}" --no-git-tag-version
    - npm publish
  tags:
    - kubernetes

