################################################################################
# Node-RED Stack or Compose
################################################################################
# docker stack deploy node-red --compose-file docker-compose-node-red.yml
# docker-compose -f docker-compose-node-red.yml -p myNoderedProject up
################################################################################
version: "3.7"

services:
  node-red:
    image: nodered/node-red:latest
    environment:
      - TZ=Europe/Kiev
    ports:
      - "1880:1880"
      - "5555:5555/udp"
      - "4444:4444"
    networks:
      - node-red-net
    volumes:
      - ./data:/data
      - ./:/workspace

  mqtt:
    image: eclipse-mosquitto
    container_name: mqtt
    ports:
      - "1883:1883" #default mqtt port
      - "9001:9001" #default mqtt port for websockets
    volumes:
      - ./mqtt-data/config:/mosquitto/config:rw
      - ./mqtt-data/data:/mosquitto/data:rw
      - ./mqtt-data/log:/mosquitto/log:rw

networks:
  node-red-net:
